### ISSUE TITLE
Can't find the file latlon.json

### ISSUE THREAD

**Issue by bemanuel** [cowboysdude/MMM-NOAA3#13]
Whoops! There was an uncaught exception...
{ Error: ENOENT: no such file or directory, open 'modules/MMM-NOAA3/latlon.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at Object.addModuleConfiguration (/home/sarnambi/MagicMirror/modules/MMM-NOAA3/providers/yw.js:71:21)
    at Class.socketNotificationReceived (/home/sarnambi/MagicMirror/modules/MMM-NOAA3/node_helper.js:40:27)
    at Socket.<anonymous> (/home/sarnambi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /home/sarnambi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'modules/MMM-NOAA3/latlon.json' }

**Comment by cowboysdude** [comment]
That's because it no longer uses that method for Lat and Lon see example config from the instructions:

{
     module: 'MMM-NOAA3',
 position: 'top_left',
     config: {
 	    provider: "Yahoo",   
 	    airKey: "YOUR API KEY", 
         css: "NOAA3",                 // THIS MUST CONTAIN A CSS STYLE NAME 
 	userlat: "xxxx", //MUST HAVE BOTH
         userlon: "xxxx"  //MUST HAVE BOTH
 }
 },

You must input your lat and lon into the config......   :)
