### ISSUE TITLE
No Forecast display 

### ISSUE THREAD

**Issue by MrMojo33** [cowboysdude/MMM-NOAA3#49]
Hello, 

at first, sorry for my english i try my best to discribe my problem. The 4 day forecast doesnt show in this module. My config check ist okay:

`~/MagicMirror $ npm run config:check

> magicmirror@2.11.0 config:check /home/pi/MagicMirror
> node tests/configs/check_config.js`

Checking file...  /home/pi/MagicMirror/config/config.js
Your configuration file doesn't contain syntax errors :)

If the magicmirror starts, it gives me the following error:

`
[2020-05-20 15:18:11.786] [ERROR]  TypeError: Cannot read property 'length' of undefined
    at Object.parseForecast (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:179:42)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:51:17)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
[2020-05-20 15:18:11.794] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-05-20 15:18:11.795] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-05-20 15:18:12.250] [LOG]    Whoops! There was an uncaught exception...
[2020-05-20 15:18:12.253] [ERROR]  TypeError: Cannot read property 'pollution' of undefined
    at Object.parseAIR (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:265:35)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:111:27)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
[2020-05-20 15:18:12.256] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?`

These are my configs:

` {
                        module: "MMM-NOAA3",
                        position: "top_left",
                        config: {
                                provider: "openweather", // From list above
                                apiKey: "MYAPIKEY", // From one of the providers listed above
                                appID: "",
                                airKey: "",
                                css: "NOAA1",// THIS MUST CONTAIN A CSS STYLE NAME
                                updateInterval: 1 * 60 * 1000,
                                userlat: "51.179089", //MUST HAVE BOTH
                                userlon: "14.317590"//MUST HAVE BOTH
                        }
`
I hope you can help me with this Problem. Thank you.

With kind regards

Mr Mojo

**Comment by shortyhn** [comment]
Same for me...

**Comment by cowboysdude** [comment]
I will have to look at openweather to see.  I KNOW there's a problem with a couple providers not sending data back.

**Comment by arturbullach** [comment]
I have nearly the same problem here. 
1st of all the module is working. 
Provider openweather.
At the bottom the is the section for 4 days forecast, but just as button. I can't get it to run like in the module description with nice icons for it. 
If somebody can help me on this i would be very happy.

**Comment by plumcraft** [comment]
Looks like, I have the same issue 

Here the logs 

```
0|mm       | [2020-09-08 19:43:35.782] [ERROR]  TypeError: Cannot read property 'length' of undefined
0|mm       |     at Object.parseForecast (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:179:42)
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ow.js:51:17)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
0|mm       |     at Request.emit (events.js:200:13)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1154:10)
0|mm       |     at Request.emit (events.js:200:13)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1076:12)
0|mm       |     at Object.onceWrapper (events.js:288:20)
0|mm       |     at IncomingMessage.emit (events.js:205:15)
0|mm       |     at endReadableNT (_stream_readable.js:1154:12)
0|mm       | [2020-09-08 19:43:35.784] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
```

as @cowboysdude comment, looks like openweather is not sending forecast data

**Comment by arturbullach** [comment]
I'm not sure about it. But I think in the free version of openweather you don't have that big forecast.

**Comment by cowboysdude** [comment]
Alot of providers have changed the way they do things.  Yes if you have a free account you may not get as much as you used to and it may break NOAA but I have no plans on a total rewrite.   The options are you can fork it and remove anything that doesn't work or just set those values to 'None' or 'null'.    I am frustrated with weather api's as I don't see why anyone should have to pay for that type of data.  Sorry if this is causing anyone a problem.
